# MERV reporting for Cucumber-js (see merv-client FRAMEWORK_INTEGRATION.md)

# Local HTML/JSON reports under merv-reports/
merv.local=false
merv.regression_suite=Automation Practice Cucumber
merv.sprint=1
merv.screenshot=true
merv.zip.export=true
merv.server=http://localhost:7777/api/v1
merv.local=false
merv.api_key=merv_732c9795d34e415587e1f10d6e609198
#merv.parent_hierarchy=your-hierarchy-uuid
merv.append_suite=10222369-0ab5-438b-8a00-b96b7042a8dd


# Merv-Server (uncomment and set your API key + hierarchy UUID)
# merv.local=false
# merv.server=https://merv.online/api/v1
# merv.api_key=your-api-key
# merv.parent_hierarchy=your-hierarchy-uuid
